### ISSUE TITLE
Source Code for Disable.dll driver file

### ISSUE THREAD

**Issue by apurv1305** [TrueOpenVR/TrueOpenVR-Drivers#13]
Hello, I was hoping to get the Source code files for the `Disable.dll` driver file, but I cannot find that file even in the Source code zip provided in the Release section. It would be very helpful if you could provide that file.

Thanks.

**Comment by r57zone** [comment]
Hello, [here it is](https://github.com/TrueOpenVR/TrueOpenVR-Drivers/tree/master/C%2B%2B/Sample), but it has been replaced name. It won't disable your Oculus Quest controllers or other devices. It only works within this project, because it has such an architecture.

If you want to disable the Oculus controller, then you need to use either the OpenVR driver that works over WiFi (it seems ALVR) and look for an opportunity there, or use some drivers (like the openvr input emulator, it doesn't seem to work now) that change the behavior of others drivers (for example, the official Oculus driver).

**Comment by apurv1305** [comment]
Thank You Sir. I don't own a Oculus, I was just trying to figure out how the drivers disable or enable an individual device.

I wanted to know about the architecture of these drivers and software, how they work, how does the data flows through all these software pieces. It would be a great help if you could brief about how this architecture is implemented and operates. I guess it's based on OpenVR?

I was wondering about having a driver under TrueOpenVR which could be controlled by a user defined custom python scripts (with a fixed output data format), that would just make the system more flexible and universal, I guess. Is it possible?

Thanks.

**Comment by apurv1305** [comment]
Thank You for the file sir.

I would give those hacks a go.

I wanted to know about the architecture of these drivers and software, how they work, how does the data flows through all these software pieces. It would be a great help if you could brief about how this architecture is implemented and operates. I guess it's based on OpenVR?

I was wondering about having a driver under TrueOpenVR which could be controlled by a user defined custom python scripts (with a fixed output data format), that would just make the system more flexible and universal, I guess. Is it possible?

Thanks.

**Comment by r57zone** [comment]
The TrueOpenVR-SteamVR driver based on OpenVR sample driver. There is no python support. It seems that ALVR had FreePie IMU support, you can write scripts there.

**Comment by apurv1305** [comment]
Okay! Do you know any resources where I can possibly have a deeper understanding for OpenVR (except official documentations), or even TrueOpenVR?

I would definitely check ALVR out.

Thanks.

**Comment by r57zone** [comment]
Maybe this will be useful:
https://github.com/finallyfunctional/openvr-driver-example/wiki
https://www.youtube.com/watch?v=LzEIOBnbC8k
